// ui/pages/mod.slint

export { CatalogPage } from "catalog_page.slint";
export { CatalogItemData } from "catalog_item_row.slint";
export { CustomersPage } from "customers_page.slint";
export { DashboardPage } from "dashboard_page.slint";
export { FundsPage } from "funds_page.slint";
export { InventoryPage } from "inventory_page.slint";
export { StockItemData } from "inventory_stock_row.slint";
export { MovementItemData } from "inventory_movement_row.slint";
export { WarehouseItemData } from "warehouse_row.slint";
export { InvoicesPage } from "invoices_page.slint";
export { SettingsPage } from "settings_page.slint";
export { UsersPage } from "users_page.slint";
