// ui/pages/mod.slint

export { CatalogPage } from "catalog_page.slint";
export { CustomersPage } from "customers_page.slint";
export { DashboardPage } from "dashboard_page.slint";
export { FundsPage } from "funds_page.slint";
export { InventoryPage } from "inventory_page.slint";
export { InvoicesPage } from "invoices_page.slint";
export { SettingsPage } from "settings_page.slint";
export { UsersPage } from "users_page.slint";
