// ui/components/rtl_text_field.slint

import { RtlLabel } from "rtl_label.slint";
import { RtlLineEdit } from "rtl_line_edit.slint";

export component RtlTextField inherits Rectangle {
    in property <string> label;
    in property <string> placeholder-text;
    in property <bool> enabled: true;
    in-out property <string> text;
    callback accepted(string);
    callback edited(string);
    min-height: root.width < 520px ? 78px : 34px;

    if root.width >= 520px : HorizontalLayout {
        spacing: 12px;

        RtlLineEdit {
            horizontal-stretch: 1;
            text <=> root.text;
            placeholder-text: root.placeholder-text;
            enabled: root.enabled;
            accepted(value) => { root.accepted(value); }
            edited(value) => { root.edited(value); }
        }
        RtlLabel { text: root.label; }
    }

    if root.width < 520px : VerticalLayout {
        spacing: 6px;

        RtlLabel {
            width: parent.width;
            height: 28px;
            text: root.label;
        }
        RtlLineEdit {
            height: 38px;
            text <=> root.text;
            placeholder-text: root.placeholder-text;
            enabled: root.enabled;
            accepted(value) => { root.accepted(value); }
            edited(value) => { root.edited(value); }
        }
    }
}
